### ISSUE TITLE
Support for Planck

### ISSUE THREAD

**Issue by radmen** [poulainpi/oryx-with-custom-qmk#2]
Planck is no longer available to be purchased from ZSA; however, Oryx still supports it. I tried to use your workflow to build config for my keyboard, but it failed. 

I was hoping that a [simple change with the paths](https://github.com/poulainpi/oryx-with-custom-qmk/commit/9711aa8639ebdf6a37f0a9e28a88dbbbcae4dbeb) will make it work, but unfortunately it fails.

Unfortunately, I'm unable to troubleshoot it, so I'm kindly asking if you could help with that. If not, that's fine too :)

Thanks for the tool. You reminded me to keep the backups somewhere.

**Comment by poulainpi** [comment]
I took a look, and good news—the workflow already supports the Planck! To use it, just set "planck_ez" as the layout_geometry. I've also added it to the keyboard list to make it easier to find.

Let me know if you run into any other issues, happy to help!

**Comment by radmen** [comment]
@poulainpi Thank you! I checked my stuff again, and I did one thing wrong. I tried to compile moonlander layout for planck...

I selected my layout, and used `planck_ez/glow` instead. It compiled; however, the workflow failed to upload the artifact:

![image](https://github.com/user-attachments/assets/858d487b-3007-40f8-9f8e-7bcb6506497c)

Not sure how to fix it, but will give it a try later.

**Comment by poulainpi** [comment]
Thanks for your investigation! 
I missed the glow version, but I’ve just pushed support for it! 
Let me know if anything goes wrong
