### ISSUE TITLE
Support for ergodox-ez-st

### ISSUE THREAD

**Issue by Sleeepy2** [poulainpi/oryx-with-custom-qmk#4]
Looks to be a similar error to the Planck during Fetch and build layout action.

I've tried using both ergodox-ez-st, and ergodox_ez.

My layout link is https://configure.zsa.io/ergodox-ez-st/layouts/GMKaj/latest/0

Using ergodox-ez-st fails here
![image](https://github.com/user-attachments/assets/ee08f361-cfcc-4c7c-b480-c80190740374)

Using  ergodox_ez fails trying to build the layout more error after the screen shot
![image](https://github.com/user-attachments/assets/05ad32c2-e75f-4eb8-9c04-df64e26c9154)

**Comment by poulainpi** [comment]
Thanks for reporting this. To get it working, you need to input ergodox_ez/stm32/glow as the keyboard type. I just pushed the addition to the list of available keyboards.

Please give it a try and let me know if you run into any further issues!

**Comment by Sleeepy2** [comment]
ran without issue. I switched to QMK before but missed some of the Oryx features. This fixes that perfectly. Thank you
